name: ci-cd
on:
 workflow_dispatch:
 push:
  branch:
    - master
    - develop

jobs:
  build-push:
    uses: github-reusable/.github/workflow/build-push.yml@master
    with:
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      #DB_PASS: ${{ secrets.DB_PASS }}
    secrets: inherit