name: ci-cd
on:
 workflow_dispatch:
 push:
  branch:
    - master
    - develop

jobs:
  build-push:
       uses: github-reusable/.github/workflow/build-push.yml
       with:
        DB_USERNAME: ${{ vars.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASS }}